apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-sample
  annotations:
    github.com/project-slug: mknet3/backstage-sample
spec:
  type: other
  lifecycle: unknown
  owner: team-a
